name: frontend
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  font_awesome_flutter: ^10.7.0
  rive: ^0.13.0
  cupertino_icons: ^1.0.8
  http: ^1.6.0
  url_launcher: ^6.3.2
  intl: ^0.20.2
  flutter_svg: ^2.2.3
  fl_chart: ^0.66.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  # Thư viện tạo icon phải nằm trong dev_dependencies
  flutter_launcher_icons: ^0.13.1

# Cấu hình icon nằm riêng biệt, không thụt lề
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/logo.png" 
  adaptive_icon_background: "#FFFFFF"

flutter:
  uses-material-design: true
  # Toàn bộ assets chỉ khai báo 1 lần duy nhất ở đây
  assets:
    - assets/animations/login_bear.riv
    - assets/logo/musicx_logo.svg
    - assets/logo/logo.png